# Generated by Django 5.2.5 on 2026-07-07 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('verification_type', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('verification_status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Abandoned', 'Abandoned')], default='Pending', max_length=20)),
                ('verification_value', models.CharField(blank=True, max_length=255, null=True)),
                ('selfie_url', models.URLField(blank=True, null=True)),
                ('id_url', models.URLField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
