# Generated by Django 5.2.5 on 2025-11-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='virtual_account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, default='Rova BaaS', max_length=100, null=True),
        ),
    ]
