# Generated by Django 5.2.5 on 2026-03-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0002_user_virtual_account_name_alter_user_bank_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='virtual_account_number',
            new_name='wallet_account_number',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='virtual_account_name',
            new_name='wallet_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bank_name',
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_bank_name',
            field=models.CharField(blank=True, default='WAAS', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
