# Generated by Django 5.2.5 on 2026-07-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0003_rename_virtual_account_number_user_wallet_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dojah_reference_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='identity_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Abandoned', 'Abandoned')], default='Pending', max_length=20),
        ),
    ]
