# Generated by Django 5.2.5 on 2026-09-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0005_remove_user_dojah_reference_id_user_address_user_bvn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facial_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
