# Generated by Django 5.2.5 on 2026-10-01 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authent', '0006_user_facial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
