# Generated by Django 5.2.5 on 2025-12-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_account_name_event_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
