# Generated by Django 5.2.5 on 2026-04-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_ticketpurchase_paystack_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bank_code',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='paystack_reference',
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='credit_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='debit_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
