"""
Django settings for monieplug project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l$!1oa0q%a!3%^prsqm*xbc0h*w&5td!ntp16oy_s&ptre!25$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["monieplug.onrender.com", "127.0.0.1",
    "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monieplug',
    'event',
    'authent',
    'rest_framework',
    "rest_framework.authtoken",
    "drf_spectacular",
    "scan2pay",
]

ROVA_BAAS_TOKEN  = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzMnVJTUlnUEN4UHVfRmhqT29IZHdXaDVvanM5YXVxblRJak53RTlPaGlvIn0.eyJleHAiOjE3NjM0NDI1NDMsImlhdCI6MTc2MzQwNjU0MywianRpIjoiNWY3NTk3MzItNWEzYy00NmY3LWJlZWQtMDI2MTQ2OTljMzgyIiwiaXNzIjoiaHR0cHM6Ly9iYWFzLWF1dGguZGV2LmdldHJvdmEuY28udWsva2V5Y2xvYWsvcmVhbG1zL3JvdmEiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiY2E0Y2I3ZjktOGU5NS00MzI4LTliZDYtNGRhM2IzNmYwYzcyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiMDFKTUhBOTBWQ0pQRlBTNVhFQ01FUjFCV1ciLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXJvdmEiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2QgZW1haWwgYWRkcmVzcyBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJhZGRyZXNzIjp7fSwiY2xpZW50SG9zdCI6IjEwLjAuNC40OSIsInByZWZlcnJlZF91c2VybmFtZSI6InNlcnZpY2UtYWNjb3VudC0wMWptaGE5MHZjanBmcHM1eGVjbWVyMWJ3dyIsImNsaWVudEFkZHJlc3MiOiIxMC4wLjQuNDkiLCJjbGllbnRfaWQiOiIwMUpNSEE5MFZDSlBGUFM1WEVDTUVSMUJXVyJ9.O1uWkZSCUnTwSvk0V0sTIG2MmBzVr_9zuGUR6z4ttmy3CeW2rTmhBRjORrglO0tWtDkAN8Sj0fPJ_bQBrdnBQZIyV7j05RFq4nG92messojSi5Or0ZOOxr17E2YCGtrtOz5HonaNDRHBNrcZ7vnR2g8o7o6XCQGGNQ-0mSDKmvmFlsUc6TqSRqTec6gDd2aaJ9JDy-d23wMT0eT-8142kGCVafF9Lw1uz9OeMsDJHm_e0v6c8pPxnxQGOuw8vLZ-j-FsMYw-jnL3Ix0THUD33CKHBQeU1d82RV_9zLYy9YWuIE-ysgMLxr5yhjyxE9LHr50YXZAa3rMXDm6IQZ0LvQ"



AUTH_USER_MODEL = 'authent.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monieplug.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monieplug.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://monieplug_75y4_user:CK1HD4U9bY7JfrRe3Fa4XAi82E9Fgs0K@dpg-d469bu3uibrs73fkp4cg-a.oregon-postgres.render.com/monieplug_75y4',
        conn_max_age=600,
        ssl_require=True   # 👈 This line forces SSL
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
#EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'akubuezehousingestate.info@gmail.com'   #Replace with your email
EMAIL_HOST_PASSWORD = 'dfrn uvhl lihl loiv'   #Replace with your email password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}



CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / "django_cache",
    }
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"




