"""
Django settings for monieplug project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
import cloudinary


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l$!1oa0q%a!3%^prsqm*xbc0h*w&5td!ntp16oy_s&ptre!25$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = ["monieplug.onrender.com", "127.0.0.1",
    "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'monieplug',
    'event',
    'authent',
    'rest_framework',
    "rest_framework.authtoken",
    "drf_spectacular",
    "scan2pay",
    'cloudinary',
    'cloudinary_storage',
]

ROVA_BAAS_TOKEN  = "eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIzMnVJTUlnUEN4UHVfRmhqT29IZHdXaDVvanM5YXVxblRJak53RTlPaGlvIn0.eyJleHAiOjE3NjQ2OTcyMTIsImlhdCI6MTc2NDY2MTIxMiwianRpIjoiMjg2ZWIxYzMtZDlmOC00MDhlLWJkMTEtMjY0MjE2ZDY0NGFlIiwiaXNzIjoiaHR0cHM6Ly9iYWFzLWF1dGguZGV2LmdldHJvdmEuY28udWsva2V5Y2xvYWsvcmVhbG1zL3JvdmEiLCJhdWQiOiJhY2NvdW50Iiwic3ViIjoiY2E0Y2I3ZjktOGU5NS00MzI4LTliZDYtNGRhM2IzNmYwYzcyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoiMDFKTUhBOTBWQ0pQRlBTNVhFQ01FUjFCV1ciLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXJvdmEiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2QgZW1haWwgYWRkcmVzcyBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJhZGRyZXNzIjp7fSwiY2xpZW50SG9zdCI6IjEwMi45MC4xMDAuMjA5IiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LTAxam1oYTkwdmNqcGZwczV4ZWNtZXIxYnd3IiwiY2xpZW50QWRkcmVzcyI6IjEwMi45MC4xMDAuMjA5IiwiY2xpZW50X2lkIjoiMDFKTUhBOTBWQ0pQRlBTNVhFQ01FUjFCV1cifQ.SuMexPE2uHekJrgOrVjruzp95zjTF1jk9vSWrtTZa0EEzDUH7GysgkhqCG4mklpV2VznkBI_7ZUkaTnSpRflghiSKqLKG_WpL2LGWPOGCs4uHfiq6Gca9i_Zrgm82bMj7DGqxSiddKN-g4VrWB5WOEG_VvjPBhnRZadJ4yiIu1F6D6ZS7p63q4oc2FFeOnpycFnfws6rclRdrMStv7qDzL1Obc4bIIK5GuWAVNNV_TG9vALurM_6b40if_EsD1cvU7K77AyBWAkgYAX5HfeSCmQ-AH0xs255Jm85hnNbEaPBUgIm7pFlpl9y63Do-u9CZ0qpMWqfzG87IwpHQsdxvQ"

#PAYSTACK_SECRET_KEY = "sk_live_fa9c9d1473eeaecf3146994c2a21e931998c34c0"
PAYSTACK_SECRET_KEY = os.environ.get("PAYSTACK_SECRET_KEY")

AUTH_USER_MODEL = 'authent.User'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'monieplug.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'monieplug.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://monieplug_ydqs_user:Gc1HRLNNAhMMNC7sk8Wp6StYwtMFagaS@dpg-d4q2u32li9vc739mekf0-a.oregon-postgres.render.com/monieplug_ydqs',
        conn_max_age=600,
        ssl_require=True   # 👈 This line forces SSL
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'




EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'monieplug.eservice@gmail.com'
EMAIL_HOST_PASSWORD = 'wwpi erqo nyla ncda'  # App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER




REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
        
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.AllowAny",
    ],

    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Event API",
    "VERSION": "1.0.0",
}



CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": BASE_DIR / "django_cache",
    }
}

#MEDIA_URL = '/media/'
#MEDIA_ROOT = BASE_DIR / "media"


DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

MEDIA_URL = '/media/'



cloudinary.config(
    cloud_name='drz8m5hj2',
    api_key='663438544161794',
    api_secret= "4j2ixRIYabfIjWccKId87_EpUCQ",
)



