# Generated by Django 5.2.5 on 2026-06-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan2pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorqrcode',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='scan2pay/qrcodes/'),
        ),
    ]
